<?php
/** @var \OmniPro\Roberto\Block\Template $block */
?>

<div class="content-product">
    <div class="nav-container">
        <div class="logo-l"></div>
        <div class="row">
            <div class="icon-search"></div>
            <div class="icon-heart"></div>
            <div class="icon-bag"></div>
            <div class="icon-burger"></div>
        </div>
    </div>
    <div class="product-details">
        <div class="image-product"></div>
        <div class="title-product">
            <p>
                Pantalones para Dama "The Sideswept Dhoti"
            </p>
            <div class="qualify">
                <div class="star-row">
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                </div>
                4 de 5
            </div>
            <p class="price">$139.99</p>
        </div>
    <div class="product-settings">
        <div class="size-row">
            <p>TAMAÑO</p>
            <div class="wrapper-sizes">
                <div class="size disable-size">S</div>
                <div class="size enable-size">M</div>
                <div class="size selected-size">L</div>
                <div class="size disable-size">XL</div>
                <div class="size disable-size">XXL</div>
            </div>
        </div>
        <div class="kit-row">
            <p>Kit</p>
            <div class="wrapper-kit">
                <div class="kit selected">HOME</div>
                <div class="kit">AWAY</div>
                <div class="kit">THIRD</div>
            </div>
        </div>
        <div class="quantity">
            <label for="selector-quantity">CANTIDAD</label>
            <input type="number" name="selector-quantity" id="selector-quantity">
        </div>
        <div class="submit">
            <input type="button" value="AÑADIR AL CARRITO">
        </div>
    </div>
    <div class="description">
        <p class="d-title">Descripción</p>
        <p class="d-text">
            lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet...
        </p>
        <p class="read-more">
            LEER MÁS
        </p>
    </div>
    <div class="recommendations">
        <p class="r-title" >También te podriá gustar</p>
        <div class="slider">
            <div class="sugggested-product">
                <div class="sp-image"></div>
                <div class="sp-info">
                    <div class="sp-title">Producto 1</div>
                    <div class="sp-price">$130</div>
                </div>
            </div>
            <div class="sugggested-product">
                <div class="sp-image"></div>
                <div class="sp-info">
                    <div class="sp-title">Producto 2</div>
                    <div class="sp-price">$130</div>
                </div>
            </div>
            <div class="sugggested-product">
                <div class="sp-image"></div>
                <div class="sp-info">
                    <div class="sp-title">Producto 3</div>
                    <div class="sp-price">$130</div>
                </div>
            </div>
        </div>
    </div>
</div>