<?php
/** @var \OmniPro\Roberto\Block\Template $block */
?>

<div class="content-product">
    <div class="nav-container">
        <div class="logo-l"></div>
        <div class="row">
            <div class="icon-search"></div>
            <div class="icon-heart"></div>
            <div class="icon-bag"></div>
            <div class="icon-burger"></div>
        </div>
    </div>
    <div class="product-details">
        <div class="image-product"></div>
        <div class="title-product">
            <p>
                Pantalones para Dama "The Sideswept Dhoti"
            </p>
            <div class="qualify">
                <div class="star-row">
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                    <div class="start"></div>
                </div>
                4 de 5

            </div>
            <p class="price">$139.99</p>
        </div>
    </div>
</div>