<div class="content-form background-login">

   <div class="logo">
      <img src=<?php echo $block->getViewFileUrl('images/logo.svg'); ?> alt="">

   </div>
   
   <form>
      <div class="tabs">
         <div class="tab">
            <input class="tab-selection" type="radio" id="tab-1" name="tab-group-1" checked />
            <div class="tab-label tab-label-rigth">
               <label  for="tab-1">INGRESO</label>    
            </div>
            <div class="content">
               <div class="form-input">
                  <label for="email">EMAIL</label>
                  <input type="text" name="email" id="email" placeholder="ejemplo@email.com">
               </div>
               <div class="form-input">
                  <label for="password">CONTRASEÑA</label>
                  <input type="password" name="password" id="password" placeholder="********">
               </div>
               <div class="form-input">
                  <input type="button" name="submit" id="submit" value="Ingreso">
               </div>
               <div class="form-input mb-2 ta-center">
                  <a href="#"> Olvide Contraseña</a>
               </div>

            </div>
         </div>
         <div class="tab">
            <input class="tab-selection" type="radio" id="tab-2" name="tab-group-1" />
            <div class="tab-label tab-label-left">
               <label  for="tab-2">REGISTRO</label>
            </div>
            <div class="content"> 
            <div class="form-input">
                  <label for="name">NOMBRE</label>
                  <input type="text" name="name" id="name" placeholder="Juan">
               </div>
               <div class="form-input">
                  <label for="lastname">Apellido</label>
                  <input type="text" name="lastname" id="lastname" placeholder="Pérez">
               </div>
               <div class="form-input">
                  <label for="email">EMAIL</label>
                  <input type="text" name="email" id="email" placeholder="ejemplo@email.com">
               </div>
               <div class="form-input">
                  <label for="password">CONTRASEÑA</label>
                  <input type="password" name="password" id="password" placeholder="********">
               </div>
               <div class="form-input">
                  <input type="button" name="submit" id="submit" value="Registro">
               </div>
            </div>
         </div>


      </div>
   </form>

</div>