<?php

/** @var \OmniPro\Prueba\Block\Template $block */
?>
<div class="blog_post">

    <?php 

   print_r( $block->getPostCollection());
        // foreach ($block->getPostCollection() as $key=>$post){
        //     echo '
        //     <div class="item_post">
        //     <h4>'.$post->getPostId().'</h4>
            
        //     <img src="" alt="">
        //     <p>'.$post->getPostContent().'</p>
        
        //     </div>
        //     ';
        // }
    ?>
    <!-- <div class="item_post">
        <h4>Title</h4>
        <img src="" alt="">
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni, iste alias omnis odio iusto molestiae eos iure a excepturi commodi, reprehenderit veniam at facilis. Reprehenderit, autem! Minima ea dolorem nulla.</p>
    
    </div>
    <div class="item_post">
        <h4>Title</h4>
        <img src="" alt="">
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni, iste alias omnis odio iusto molestiae eos iure a excepturi commodi, reprehenderit veniam at facilis. Reprehenderit, autem! Minima ea dolorem nulla.</p>
    
    </div> -->

</div>